### ISSUE TITLE
Vuebar adds padding-right: 20px instead of width in Safari.

### ISSUE THREAD

**Issue by kirill001** [DominikSerafin/vuebar#42]
WHen I open my website on Safari I see extra space on the right side. The reason is` padding-right:20px `and lack of `width: (100% - 15px);`
In Chrome it works perfectly and there is no rule `padding-right:20px` but there is `width:calc(100% - 15px)`.
If I change manually these rules in Safari's console (remove padding and add width:calc(100%-15px)) it also works.
How to fix this behavior? Please help.

**Comment by DominikSerafin** [comment]
Hi @kirill001, I can't reproduce it. Could you provide jsfiddle with minimal reproduction? Without it I'm not able to help you.

Here's good starting point: http://jsfiddle.net/u94ns8jc/1/

**Comment by kirill001** [comment]
Your example works.
Can you please visit [my website ](https://bandwidget.com/id93/?title=Metallica&theme=light&channels=facebook,twitter,youtube,vevo,itunes,amazon,soundcloud,bit,ticketfly,event,media)
I can't realize why I have the space.

**Comment by kirill001** [comment]
I guess I have found the reason.
If I fill <--el2--> with plain text it works, but If I put there div elements I see extra space.
There is an example  `https://codepen.io/anon/pen/LOKMog`
And the screenshot from Safari 
![2017-12-08 12-40-48 an anonymous pen on codepen](https://user-images.githubusercontent.com/8287881/33762580-b5dd77e2-dc15-11e7-9fff-04edbe1d8607.png)

**Comment by filipenco92** [comment]
Hello, how resolve this problem: http://joxi.ru/ZrJk3vxT1y5xjm , I set margin-right: -20px but this is not very good solution!

**Comment by DominikSerafin** [comment]
Hey @kirill001 @filipenco92, I've just merged a fix for this. Could you confirm that this is fixed now for you in Vuebar v0.0.18?

**Comment by scherii** [comment]
Hey @DominikSerafin
This fixed it for me, thank you very much! 🙂

**Comment by filipenco92** [comment]
@DominikSerafin Hello, I install now vuebar 0.0.18 and tried, but this not fixed it: http://joxi.ru/5mdBweKUvg1ggA! maybe i do not understand something, but it should be : http://joxi.ru/1A5GjVEtKYk5Mm, and for this i write to vb-content width: calc(100% + 20px) or for dropdown item margin-right: -20px because vb-content have padding-right: 20px and this padding push overflow but clear space remains! sorry for my bad english :)

**Comment by DominikSerafin** [comment]
@filipenco92 I think the problem is with `margin-right: -20px`, try deleting it.

If it wont work, can you provide minimal reproduction of your problem and tell me in which os/browser it doesn't work?

Starting points with Vue+Vuebar:
http://jsfiddle.net/u94ns8jc/1/
https://www.webpackbin.com/bins/-Kyoqtm8CbjpkYegi7mF

**Comment by filipenco92** [comment]
@DominikSerafin this problem exist in inactive tab, or dropdown, reproduction problem (browser Chrome, os Ubuntu): http://jsfiddle.net/filipenco92/b4u9dxnk/4/

**Comment by DominikSerafin** [comment]
@filipenco92 , thank you for the reproduction, now I know now where the problem lies. 

It's a little different problem from this one, so I've created new issue for this: https://github.com/DominikSerafin/vuebar/issues/46

**Comment by DominikSerafin** [comment]
@filipenco92 , investigated it further and it seems it's not a problem with Vuebar, but rather your implementation of these tabs.

You've used jQuery to implement them instead using Vue state. This way you've forbidden Vuebar to be able to listen to updates to state and it couldn't refresh/initialize properly.

As a workaround for this, you can use public methods to destroy/reinitialize Vuebar on every tab change.
See working demo: http://jsfiddle.net/b4u9dxnk/12/

The workaround is a little messy, but it works. You can improve it from here further. 

I've added there `refreshScrollbars` method which gets called when you click on tabs/dropdown. And it destroys every Vuebar instance, and then re-initializes it. It seems like jQuery is actually pretty slow in updating the DOM, so I had to wrap that code in timeout > 200. Otherwise it wasn't working.

**Comment by filipenco92** [comment]
@DominikSerafin ok, thanks, i tried with bootstrap-vue (https://bootstrap-vue.js.org) and in tabs and dropdown is the same problem, i will use refreshScrollbars!

**Comment by kirill001** [comment]
@DominikSerafin Perfect! Now it works! Thank you!

**Comment by avilesasturias** [comment]
Hi,
It was probably asked many times, but whenever the element has padding on it, the browser scrollbar becomes visible?
Is this normal behaviour? [jsfiddle](http://jsfiddle.net/4uh7pzj3/)
